FROM node:20-bookworm AS builder

RUN apt-get update && apt-get install -y curl gettext-base jq

WORKDIR /root
COPY ./stacking/package.json /root/
RUN npm i

COPY ./stacking/deployments/*.yaml /root/deployments/
COPY ./stacking/contracts/*.clar /root/contracts/
COPY ./stacking/.cache/requirements/*.clar /root/.cache/requirements/
COPY ./stacking/*.ts /root/

CMD ["npx", "tsx", "/root/stacking.ts"]